# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arcanine/Portfolio/Raytracer---LBVH

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arcanine/Portfolio/Raytracer---LBVH

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arcanine/Portfolio/Raytracer---LBVH/CMakeFiles /home/arcanine/Portfolio/Raytracer---LBVH//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arcanine/Portfolio/Raytracer---LBVH/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/arcanine/Portfolio/Raytracer---LBVH/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vk-bootstrap

# Build rule for target.
vk-bootstrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vk-bootstrap
.PHONY : vk-bootstrap

# fast build rule for target.
vk-bootstrap/fast:
	$(MAKE) $(MAKESILENT) -f external/vk-bootstrap/CMakeFiles/vk-bootstrap.dir/build.make external/vk-bootstrap/CMakeFiles/vk-bootstrap.dir/build
.PHONY : vk-bootstrap/fast

#=============================================================================
# Target rules for targets named SDL3-shared

# Build rule for target.
SDL3-shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3-shared
.PHONY : SDL3-shared

# fast build rule for target.
SDL3-shared/fast:
	$(MAKE) $(MAKESILENT) -f external/vendored/SDL/CMakeFiles/SDL3-shared.dir/build.make external/vendored/SDL/CMakeFiles/SDL3-shared.dir/build
.PHONY : SDL3-shared/fast

#=============================================================================
# Target rules for targets named SDL3_test

# Build rule for target.
SDL3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3_test
.PHONY : SDL3_test

# fast build rule for target.
SDL3_test/fast:
	$(MAKE) $(MAKESILENT) -f external/vendored/SDL/CMakeFiles/SDL3_test.dir/build.make external/vendored/SDL/CMakeFiles/SDL3_test.dir/build
.PHONY : SDL3_test/fast

#=============================================================================
# Target rules for targets named SDL_uclibc

# Build rule for target.
SDL_uclibc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL_uclibc
.PHONY : SDL_uclibc

# fast build rule for target.
SDL_uclibc/fast:
	$(MAKE) $(MAKESILENT) -f external/vendored/SDL/CMakeFiles/SDL_uclibc.dir/build.make external/vendored/SDL/CMakeFiles/SDL_uclibc.dir/build
.PHONY : SDL_uclibc/fast

#=============================================================================
# Target rules for targets named engine

# Build rule for target.
engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine
.PHONY : engine

# fast build rule for target.
engine/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/engine.dir/build.make src/CMakeFiles/engine.dir/build
.PHONY : engine/fast

#=============================================================================
# Target rules for targets named bvh

# Build rule for target.
bvh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bvh
.PHONY : bvh

# fast build rule for target.
bvh/fast:
	$(MAKE) $(MAKESILENT) -f src/bvh/CMakeFiles/bvh.dir/build.make src/bvh/CMakeFiles/bvh.dir/build
.PHONY : bvh/fast

#=============================================================================
# Target rules for targets named raytracer

# Build rule for target.
raytracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raytracer
.PHONY : raytracer

# fast build rule for target.
raytracer/fast:
	$(MAKE) $(MAKESILENT) -f src/raytracer/CMakeFiles/raytracer.dir/build.make src/raytracer/CMakeFiles/raytracer.dir/build
.PHONY : raytracer/fast

#=============================================================================
# Target rules for targets named vulkan_engine

# Build rule for target.
vulkan_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vulkan_engine
.PHONY : vulkan_engine

# fast build rule for target.
vulkan_engine/fast:
	$(MAKE) $(MAKESILENT) -f src/vulkan_engine/CMakeFiles/vulkan_engine.dir/build.make src/vulkan_engine/CMakeFiles/vulkan_engine.dir/build
.PHONY : vulkan_engine/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SDL3-shared"
	@echo "... SDL3_test"
	@echo "... SDL_uclibc"
	@echo "... bvh"
	@echo "... engine"
	@echo "... raytracer"
	@echo "... vk-bootstrap"
	@echo "... vulkan_engine"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/arcanine/Portfolio/Raytracer---LBVH/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

