#version 460
#extension GL_GOOGLE_include_directive : require
#include "bvh_include.glsl"

#define K 10
#define CELL_COUNT (1 << K)

void main() {
  uint thread = gl_GlobalInvocationID.x;
  if (thread >= primitiveCount) return;
  uint leaf_idx = thread + primitiveCount - 1;

  float barycenterx = (corner2x[leaf_idx] + corner1x[leaf_idx]) * 0.5;
  float barycentery = (corner2y[leaf_idx] + corner1y[leaf_idx]) * 0.5;
  float barycenterz = (corner2z[leaf_idx] + corner1z[leaf_idx]) * 0.5;

  float xCell = CELL_COUNT * (barycenterx - worldBbox.corner1x) / (worldBbox.corner2x - worldBbox.corner1x);
  float yCell = CELL_COUNT * (barycentery - worldBbox.corner1y) / (worldBbox.corner2y - worldBbox.corner1y);
  float zCell = CELL_COUNT * (barycenterz - worldBbox.corner1z) / (worldBbox.corner2z - worldBbox.corner1z);

  uint x = min(uint(xCell), CELL_COUNT - 1);
  uint y = min(uint(yCell), CELL_COUNT - 1);
  uint z = min(uint(zCell), CELL_COUNT - 1);

  uint code = 0;
  for (int j = 0; j < K; j++) {
    code |= ((x >> j) & 1) << (3 * j);
    code |= ((y >> j) & 1) << (3 * j + 1);
    code |= ((z >> j) & 1) << (3 * j + 2);
  }

  mortonCodes[thread] = code;
  primIndices[thread] = thread;
}
