#version 460
#extension GL_GOOGLE_include_directive : require
#include "bvh_include.glsl"

void main() {
  uint idx = gl_GlobalInvocationID.x;
  if (idx >= primitiveCount) return;

  // Create bbox
  triangle tri = scene.triangles[idx];
  uint leaf_idx = idx + primitiveCount - 1;

  corner1x[leaf_idx] = min(tri.v0.x, min(tri.v1.x, tri.v2.x));
  corner1y[leaf_idx] = min(tri.v0.y, min(tri.v1.y, tri.v2.y));
  corner1z[leaf_idx] = min(tri.v0.z, min(tri.v1.z, tri.v2.z));
  corner2x[leaf_idx] = max(tri.v0.x, max(tri.v1.x, tri.v2.x));
  corner2y[leaf_idx] = max(tri.v0.y, max(tri.v1.y, tri.v2.y));
  corner2z[leaf_idx] = max(tri.v0.z, max(tri.v1.z, tri.v2.z));
}
