#version 460

struct triangle {
  vec4 v0; vec4 v1; vec4 v2;
  vec4 n0; vec4 n1; vec4 n2;
  vec2 uv0; vec2 uv1; vec2 uv2;

  int mat_index;
  int _pad;
};

struct hit_record {
    vec3 p;
    vec3 normal;
    int mat_index;
    float t; 
    vec2 uv;
    bool front_face;
};

const float EPSILON = 1e-8;

bool intersect_triangle(
  vec3 ray_origin, vec3 ray_dir, float t_closest, 
  triangle tri, out hit_record rec) 
{
  vec3 edge1 = tri.v1.xyz - tri.v0.xyz;
  vec3 edge2 = tri.v2.xyz - tri.v0.xyz;
  vec3 h = cross(ray_dir, edge2);
  float a = dot(edge1, h);

  if(abs(a) < EPSILON) return false;

  float f = 1.0 / a;
  vec3 s = ray_origin - tri.v0.xyz;
  float u = f * dot(s, h);

  if (u < 0.0 || u > 1.0) return false;

  vec3 q = cross(s, edge1);
  float v = f * dot(ray_dir, q);

  if (v < 0.0 || u + v > 1.0) return false;

  float t = f * dot(edge2, q);

  if (t < EPSILON || t > t_closest) return false;

  rec.t = t;
  rec.p = ray_origin + t * ray_dir;

  float w = 1.0 - u - v;
  vec3 outward_normal = normalize(
    w * tri.n0.xyz +
    u * tri.n1.xyz +
    v * tri.n2.xyz
  );

  rec.front_face = dot(ray_dir, outward_normal) < 0;
  rec.normal = rec.front_face ? outward_normal : -outward_normal;

  rec.uv = w * tri.uv0 + u * tri.uv1 + v * tri.uv2;
  rec.mat_index = tri.mat_index;

  return true;
}

layout(local_size_x = 16, local_size_y = 16) in;
layout(push_constant) uniform Camera {
    vec4 center;
    vec4 pixel00_loc;
    vec4 pixel_delta_u;
    vec4 pixel_delta_v;
} cam;
layout(binding = 1, std430) readonly buffer SceneBuffer {
    triangle triangles[];
} scene;

layout(binding = 0, rgba8) uniform writeonly image2D img;

void main() {
  ivec2 thread = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imgSize = imageSize(img);

  if (thread.x < imgSize.x && thread.y < imgSize.y) {
    // calculate pixel position in world
    vec3 pixel_pos = 
      cam.pixel00_loc.xyz + 
      float(thread.x) * cam.pixel_delta_u.xyz + 
      float(thread.y) * cam.pixel_delta_v.xyz;

    vec3 ray_dir = normalize(pixel_pos - cam.center.xyz);

    hit_record rec;
    rec.t = 1e30;

    for (int i = 0; i < scene.triangles.length(); i++) {
      hit_record temp_rec;
      if (intersect_triangle(cam.center.xyz, ray_dir, rec.t, scene.triangles[i], temp_rec)) {
        rec = temp_rec;
      }
    }

    // Simple shading to check if hit records work
    vec3 background_color = vec3(0.7, 0.6, 1.0);
    vec3 surface_color = vec3(0.4, 0.6, 0.4);
    vec3 light_dir = vec3(1, 2, 3);
    vec4 color = rec.t < 1e30 
      ? vec4(surface_color * max(dot(rec.normal, normalize(light_dir)), 0.0), 1) 
      : vec4(background_color, 1);
    imageStore(img, thread, color);
  }
}
