#version 460
layout(local_size_x = 16, local_size_y = 16) in;
layout(binding = 0, rgba8) uniform writeonly image2D img;

void main() {
  ivec2 thread = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imgSize = imageSize(img);

  if (thread.x < imgSize.x && thread.y < imgSize.y) {
    vec4 color = vec4( 
        vec2(thread)/vec2(imgSize),
        0,
        1);

    imageStore(img, thread, color);
  }
}
