#version 460

#include "triangle.glsl"

struct hit_record {
  vec3 p;
  vec3 normal;
  int mat_index;
  float t;
  vec2 uv;
  bool front_face;
};

const float EPSILON = 1e-8;
const float PI = 3.14159;
const int MAX_BOUNCES = 10;
const int SAMPLES = 10;

// From: https://stackoverflow.com/questions/9912143/how-to-get-a-random-number-in-opencl
//noise values in range if 0.0 to 1.0
float noise3D(float x, float y, float z) {
  return fract(sin(x * 112.9898f + y * 179.233f + z * 237.212f) * 43758.5453f);
}

bool intersect_triangle(
  vec3 ray_origin, vec3 ray_dir, float t_closest,
  triangle tri, out hit_record rec)
{
  vec3 edge1 = tri.v1.xyz - tri.v0.xyz;
  vec3 edge2 = tri.v2.xyz - tri.v0.xyz;
  vec3 h = cross(ray_dir, edge2);
  float a = dot(edge1, h);

  if (abs(a) < EPSILON) return false;

  float f = 1.0 / a;
  vec3 s = ray_origin - tri.v0.xyz;
  float u = f * dot(s, h);

  if (u < 0.0 || u > 1.0) return false;

  vec3 q = cross(s, edge1);
  float v = f * dot(ray_dir, q);

  if (v < 0.0 || u + v > 1.0) return false;

  float t = f * dot(edge2, q);

  if (t < 0.001 || t > t_closest) return false;

  rec.t = t;
  rec.p = ray_origin + t * ray_dir;

  float w = 1.0 - u - v;
  vec3 outward_normal = normalize(
      w * tri.n0.xyz +
        u * tri.n1.xyz +
        v * tri.n2.xyz
    );

  rec.front_face = dot(ray_dir, outward_normal) < 0;
  rec.normal = rec.front_face ? outward_normal : -outward_normal;

  rec.uv = w * tri.uv0 + u * tri.uv1 + v * tri.uv2;
  rec.mat_index = tri.mat_index;

  return true;
}

layout(local_size_x = 16, local_size_y = 16) in;
layout(push_constant) uniform Camera {
  vec4 center;
  vec4 pixel00_loc;
  vec4 pixel_delta_u;
  vec4 pixel_delta_v;
} cam;
layout(binding = 1, std430) readonly buffer SceneBuffer {
  triangle triangles[];
} scene;

layout(binding = 0, rgba8) uniform writeonly image2D img;

void main() {
  ivec2 thread = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imgSize = imageSize(img);

  if (thread.x < imgSize.x && thread.y < imgSize.y) {
    // calculate pixel position in world
    vec3 pixel_pos =
      cam.pixel00_loc.xyz +
        float(thread.x) * cam.pixel_delta_u.xyz +
        float(thread.y) * cam.pixel_delta_v.xyz;

    vec3 energy = vec3(0.0, 0.0, 0.0);
    vec3 BRDF = vec3(0.4, 0.6, 0.4) / PI;
    float hemiPDF = 1.0 / (PI * 2.0f);

    vec3 background_color = vec3(0.7, 0.6, 1.0);
    vec3 light_dir = normalize(vec3(1.0, 2.0, 3.0));

    for (int s = 0; s < SAMPLES; s++) {
      float seed = noise3D(float(thread.x), float(thread.y), float(s));

      vec3 ray_origin = cam.center.xyz;
      vec3 ray_dir = normalize(pixel_pos - ray_origin);

      vec3 throughput = vec3(1.0, 1.0, 1.0);
      vec3 sample_energy = vec3(0.0, 0.0, 0.0);

      for (int i = 0; i < MAX_BOUNCES; i++) {
        hit_record rec;
        rec.t = 1e30;

        for (int j = 0; j < scene.triangles.length(); j++) {
          hit_record temp_rec;
          if (intersect_triangle(ray_origin, ray_dir, rec.t, scene.triangles[j], temp_rec)) {
            rec = temp_rec;
          }
        }

        // Break if no hit
        if (rec.t >= 1e30) {
          sample_energy += throughput * background_color;
          break;
        }

        // Light
        sample_energy += 0.5 * throughput * BRDF * max(dot(rec.normal, light_dir), 0.0);

        // Continue bounces
        ray_origin = rec.p;
        float r0 = noise3D(seed, float(i) * 0.1273, rec.p.x);
        float r1 = noise3D(seed, float(i) * 0.3183, rec.p.y);
        float r2 = noise3D(seed, float(i) * 0.7123, rec.p.z);
        vec3 rand_unit_vec = normalize(vec3(r0, r1, r2) * 2.0 - 1.0);
        ray_dir = normalize(rec.normal + rand_unit_vec);
        throughput *= (max(dot(rec.normal, ray_dir), 0.0) / hemiPDF) * BRDF;
      }

      energy += sample_energy / float(SAMPLES);
    }

    imageStore(img, thread, vec4(energy, 1.0));
  }
}
