#version 460

#include "ray.glsl"

const int SAMPLES = 10;

layout(local_size_x = 16, local_size_y = 16) in;
layout(push_constant) uniform Camera {
  vec4 center;
  vec4 pixel00_loc;
  vec4 pixel_delta_u;
  vec4 pixel_delta_v;
} cam;

// TODO: pass image size with push constants
layout(binding = 0, rgba8) uniform writeonly image2D img;
layout(binding = 1, std430) writeonly buffer RaysBuffer {
  Ray rays[];
} ray_out;

void main() {
  ivec2 thread = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imgSize = imageSize(img);

  if (thread.x < imgSize.x && thread.y < imgSize.y) {
    vec3 pixel_pos = cam.pixel00_loc.xyz +
      float(thread.x) * cam.pixel_delta_u.xyz +
      float(thread.y) * cam.pixel_delta_v.xyz;

    vec3 ray_dir = normalize(pixel_pos - cam.center.xyz);

    int pixel_index = thread.y * imgSize.x + thread.x;

    for (int s = 0; s < SAMPLES; s++) {
      int sample_index = pixel_index * SAMPLES + s;
      ray_out.rays[sample_index].origin = cam.center.xyz;
      ray_out.rays[sample_index].dir = ray_dir;
    }
  }
}