#version 460
#extension GL_GOOGLE_include_directive : require

#include "triangle.glsl"
#include "ray.glsl"
#include "path_state.glsl"

const int MAX_BOUNCES = 20;
const float PI = 3.14159;

layout(local_size_x = 64) in;

// IN BUFFERS
layout(binding = 0, std430) readonly buffer RaysInBuffer {
  Ray rays[];
} ray_in;

layout(binding = 1, std430) readonly buffer PathStatesInBuffer {
  PathState states[];
} path_state_in;

layout(binding = 2, std430) readonly buffer HitRecordsBuffer {
  hit_record records[];
} hit_records;

layout(binding = 3, std430) readonly buffer LastRayCountBuffer {
  uint count;
} last_ray_count;

// OUT BUFFERS
layout(binding = 4, std430) writeonly buffer RaysOutBuffer {
  Ray rays[];
} ray_out;

layout(binding = 5, std430) writeonly buffer PathStatesOutBuffer {
  PathState states[];
} path_state_out;

layout(binding = 6, std430) writeonly buffer FinalRadianceBuffer {
  vec3 radiance[];
} final_radiance;

layout(binding = 7, std430) buffer NextRayCountBuffer {
  uint count;
} next_ray_count;

float noise3D(float x, float y, float z) {
  return fract(sin(x * 112.9898f + y * 179.233f + z * 237.212f) * 43758.5453f);
}

void main() {
  int thread = int(gl_GlobalInvocationID.x);

  if (thread < last_ray_count.count) {
    Ray ray = ray_in.rays[thread];
    hit_record rec = hit_records.records[thread];
    PathState state = path_state_in.states[thread];

    // float hemiPDF = 1.0 / (PI * 2.0f);               // Not used later on
    // vec3 light_dir = normalize(vec3(1.0, 2.0, 3.0)); // Not used later on

    // Miss
    if (rec.t >= 1e30) {
      final_radiance.radiance[state.og_path_idx] = 
        state.radiance + state.throughput * 
        vec3(0.7, 0.8, 1.0); // background color
      return;
    }

    // Light
    // vec3 radiance = state.radiance +
    //   0.5 * state.throughput * BRDF * max(dot(rec.normal, light_dir), 0.0);
    // Removed light contribution to stay consistent with the CPU tracer / baseline
    // vec3 radiance = state.radiance;                  // Not used later on

    // Exceeded max bounces
    if (state.bounce + 1 >= MAX_BOUNCES) {
      final_radiance.radiance[state.og_path_idx] = state.radiance;
      return;
    }

    // Continue bounces
    float seed = noise3D(float(thread), float(next_ray_count.count), rec.normal.x);
    vec3 new_ray_dir = normalize(
      rec.normal + 
      normalize(vec3( // Random unit vector
        noise3D(seed, float(state.bounce) * 0.1273, rec.p.x), 
        noise3D(seed, float(state.bounce) * 0.3183, rec.p.y), 
        noise3D(seed, float(state.bounce) * 0.7123, rec.p.z)
      ) * 2.0 - 1.0)
    );

    uint out_idx = atomicAdd(next_ray_count.count, 1);

    ray_out.rays[out_idx].origin = rec.p;
    ray_out.rays[out_idx].dir = new_ray_dir;

    path_state_out.states[out_idx].throughput =
      state.throughput * 
      vec3(0.4, 0.6, 0.4); // BRDF
    // (max(dot(rec.normal, new_ray_dir), 0.0) / hemiPDF) * BRDF;
    // Removed hemisphere pdf cause its not in the CPU tracer, that way images are consistent
    path_state_out.states[out_idx].radiance = state.radiance;
    path_state_out.states[out_idx].og_path_idx = state.og_path_idx;
    path_state_out.states[out_idx].bounce = state.bounce + 1;
  }
}