#version 460
#extension GL_GOOGLE_include_directive : require

#include "ray.glsl"
#include "path_state.glsl"

const int SAMPLES = 1;

layout(local_size_x = 16, local_size_y = 16) in;
layout(push_constant) uniform Camera {
  vec4 center;
  vec4 pixel00_loc;
  vec4 pixel_delta_u;
  vec4 pixel_delta_v;
} cam;

// TODO: pass image size with push constants
layout(binding = 0, rgba8) uniform writeonly image2D img;

layout(binding = 1, std430) writeonly buffer RaysBuffer {
  Ray rays[];
} ray_out;

layout(binding = 2, std430) writeonly buffer PathStateBuffer {
  PathState states[];
} path_state_out;

float noise3D(float x, float y, float z) {
  return fract(sin(x * 112.9898f + y * 179.233f + z * 237.212f) * 43758.5453f);
}

void main() {
  ivec2 thread = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imgSize = imageSize(img);
  float jx = noise3D(float(thread.x), float(thread.y), +0.5) - 0.5;
  float jy = noise3D(float(thread.x), float(thread.y), +0.91) - 0.5;
  vec3 pixel_pos = cam.pixel00_loc.xyz
      + (float(thread.x) + jx) * cam.pixel_delta_u.xyz
      + (float(thread.y) + jy) * cam.pixel_delta_v.xyz;

  if (thread.x < imgSize.x && thread.y < imgSize.y) {
    int pixel_index = thread.y * imgSize.x + thread.x;

    for (int s = 0; s < SAMPLES; s++) {
      vec3 ray_dir = normalize(pixel_pos - cam.center.xyz);

      int sample_index = pixel_index * SAMPLES + s;
      ray_out.rays[sample_index].origin = cam.center.xyz;
      ray_out.rays[sample_index].dir = ray_dir;

      path_state_out.states[sample_index].throughput = vec3(1.0, 1.0, 1.0);
      path_state_out.states[sample_index].radiance = vec3(0.0, 0.0, 0.0);
      path_state_out.states[sample_index].og_path_idx = uint(sample_index);
      path_state_out.states[sample_index].bounce = 0;
    }
  }
}
