#version 460

#include "triangle.glsl"
#include "ray.glsl"
#include "path_state.glsl"

const int MAX_BOUNCES = 10;
const float PI = 3.14159;

layout(local_size_x = 256) in;

// IN BUFFERS
layout(binding = 0, std430) readonly buffer RaysInBuffer {
  Ray rays[];
} ray_in;

layout(binding = 1, std430) readonly buffer PathStatesInBuffer {
  PathState states[];
} path_state_in;

layout(binding = 2, std430) readonly buffer HitRecordsBuffer {
  hit_record records[];
} hit_records;

// OUT BUFFERS
layout(binding = 3, std430) writeonly buffer RaysOutBuffer {
  Ray rays[];
} ray_out;

layout(binding = 4, std430) writeonly buffer PathStatesOutBuffer {
  PathState states[];
} path_state_out;

layout(binding = 5, std430) writeonly buffer FinalRadianceBuffer {
  vec3 radiance[];
} final_radiance;

layout(binding = 6, std430) buffer NextRayCountBuffer {
  uint count;
} next_ray_count;

float noise3D(float x, float y, float z) {
  return fract(sin(x * 112.9898f + y * 179.233f + z * 237.212f) * 43758.5453f);
}

void main() {
  int thread = int(gl_GlobalInvocationID.x);

  if (thread < path_state_in.states.length()) {
    Ray ray = ray_in.rays[thread];
    hit_record rec = hit_records.records[thread];
    PathState state = path_state_in.states[thread];

    vec3 BRDF = vec3(0.4, 0.6, 0.4) / PI;
    float hemiPDF = 1.0 / (PI * 2.0f);
    vec3 background_color = vec3(0.7, 0.6, 1.0);
    vec3 light_dir = normalize(vec3(1.0, 2.0, 3.0));

    // Miss
    if (rec.t >= 1e30) {
      final_radiance.radiance[state.og_path_idx] = 
        state.radiance + state.throughput * background_color;
      return;
    }

    // Compute radiance from light 
    // (also to use in case max bounces would be reached next iteration)
    vec3 radiance = state.radiance + 
      0.5 * state.throughput * BRDF * max(dot(rec.normal, light_dir), 0.0);

    // Exceeded max bounces
    if (state.bounce + 1 >= MAX_BOUNCES) {
      final_radiance.radiance[state.og_path_idx] = radiance;
      return;
    }

    // Continue bounces
    float seed = noise3D(float(thread), float(next_ray_count.count), rec.normal.x);
    float r0 = noise3D(seed, float(state.bounce) * 0.1273, rec.p.x);
    float r1 = noise3D(seed, float(state.bounce) * 0.3183, rec.p.y);
    float r2 = noise3D(seed, float(state.bounce) * 0.7123, rec.p.z);
    vec3 rand_unit_vec = normalize(vec3(r0, r1, r2) * 2.0 - 1.0);
    vec3 new_ray_dir = normalize(rec.normal + rand_unit_vec);

    uint out_idx = atomicAdd(next_ray_count.count, 1);

    ray_out.rays[out_idx].origin = rec.p;
    ray_out.rays[out_idx].dir = new_ray_dir;

    path_state_out.states[out_idx].throughput = 
      state.throughput * (max(dot(rec.normal, new_ray_dir), 0.0) / hemiPDF) * BRDF;
    path_state_out.states[out_idx].radiance = radiance;
    path_state_out.states[out_idx].og_path_idx = state.og_path_idx;
    path_state_out.states[out_idx].bounce = state.bounce + 1;
  }
}