#version 460

const int SAMPLES = 1;

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba8) uniform writeonly image2D img;

layout(binding = 1, std430) readonly buffer FinalRadianceBuffer {
  vec3 radiance[];
} final_radiance;

void main() {
  ivec2 thread = ivec2(gl_GlobalInvocationID.xy);
  ivec2 imgSize = imageSize(img);

  if (thread.x < imgSize.x && thread.y < imgSize.y) {
    int pixel_index = SAMPLES * (thread.y * imgSize.x + thread.x);

    vec3 energy = vec3(0.0f);
    for (int s = 0; s < SAMPLES; s++) {
      energy += final_radiance.radiance[pixel_index + s];
    }

    energy /= float(SAMPLES);

    energy = max(energy, vec3(0.0));

    imageStore(img, thread, vec4(energy , 1.0));
  }
}