#version 460
#extension GL_GOOGLE_include_directive : require

#include "ray.glsl"
#include "bvh_traversal.glsl"

layout(local_size_x = 256) in;

layout(binding = 0, std430) readonly buffer RaysBuffer {
  Ray rays[];
} ray_in;

layout(binding = 3, std430) writeonly buffer HitRecordsBuffer {
  hit_record records[];
} hit_records;

layout(binding = 4, std430) readonly buffer LastRayCountBuffer {
  uint count;
} last_ray_count;

void main() {
  int thread = int(gl_GlobalInvocationID.x);

  if (thread < last_ray_count.count) {
    Ray ray = ray_in.rays[thread];
    hit_record rec;
    bvh_hit(ray.origin, ray.dir, rec);
    hit_records.records[thread] = rec;
  }
}
